# Generated by Django 4.2.3 on 2023-07-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestToReview',
        ),
    ]
