# Generated by Django 4.2.3 on 2023-07-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='reviewer_1_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='reviewer_2_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='reviewer_3_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='reviewer_4_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='reviewer_5_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
