# Generated by Django 4.2.3 on 2023-07-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0008_alter_assigned_reviewer_1_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assigned',
        ),
    ]
