# Generated by Django 4.2.2 on 2023-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_proposal', models.CharField(max_length=20)),
                ('major_discipline', models.CharField(choices=[('A', 'Atmospheric Science'), ('O', 'Oceanography'), ('G', 'Geology and Palosciences'), ('R', 'Glaciology and Remote Sensing'), ('E', 'Environmental Science'), ('B', 'Biology'), ('T', 'Other')], max_length=1)),
                ('sub_theme', models.CharField(max_length=20)),
                ('key_words', models.CharField(max_length=50)),
                ('Ongoing/New', models.CharField(choices=[('O', 'Ongoing'), ('N', 'New')], max_length=1)),
                ('brief_description', models.TextField(max_length=250)),
            ],
        ),
    ]
