# Generated by Django 4.2.2 on 2023-07-01 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_details_address_details_designation_details_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('title_of_proposal', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('major_discipline', models.CharField(choices=[('Atmospheric Science', 'Atmospheric Science'), ('Oceanography', 'Oceanography'), ('Geology and Palosciences', 'Geology and Palosciences'), ('Glaciology and Remote Sensing', 'Glaciology and Remote Sensing'), ('Environmental Science', 'Environmental Science'), ('Biology', 'Biology'), ('Other', 'Other')], max_length=30)),
                ('sub_theme', models.CharField(max_length=20)),
                ('key_words', models.CharField(max_length=50)),
                ('Ongoing/New', models.CharField(choices=[('Ongoing', 'Ongoing'), ('New', 'New')], max_length=10)),
                ('brief_description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('title_of_proposal', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Attach Cover Letter', models.FileField(blank=True, null=True, upload_to='')),
                ('Attach the detailed Project proposal(Download Template (.docx file) ', models.FileField(blank=True, null=True, upload_to='')),
                ('Attach the detailed Project proposal(Download Appendix I Template (.docx file)', models.FileField(blank=True, null=True, upload_to='')),
                ('Attach Appendix II (Assessment for Ongoing project) Download Template for Appendix II', models.FileField(blank=True, null=True, upload_to='')),
                ('Attach Appendix III (Metadata format for Ongoing project)* Download Template for Appendix III', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IncompleteProposals',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
