# Generated by Django 4.2.2 on 2023-07-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_files_attach_appendix_ii_assessment_for_ongoing_project_download_template_for_appendix_ii_and_'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
