# Generated by Django 4.2.2 on 2023-07-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_details_email_files_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('is_author_approved', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
