# Generated by Django 4.2.2 on 2023-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_details_pi_10_address_details_pi_10_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='proposal_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
