# Generated by Django 4.2.2 on 2023-07-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposalmeta_details_pi_1_address_and_more'),
        ('proposals', '0008_alter_details_proposal_number'),
    ]

    operations = [
    ]
