# Generated by Django 4.2.2 on 2023-07-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_merge_20230710_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 1 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 10 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 2 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 3 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 4 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 5 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 6 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 7 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 8 Title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Designation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Gender',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Institute',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Mobile',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='PI 9 Title',
        ),
    ]
