# Generated by Django 4.2.2 on 2023-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revisers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviser_email', models.EmailField(max_length=254)),
                ('proposal_number', models.CharField(max_length=12)),
            ],
        ),
    ]
