# Generated by Django 4.2.2 on 2023-07-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('major_discipline', models.CharField(max_length=50)),
                ('pi_name', models.CharField(max_length=50)),
                ('pi_institute', models.CharField(max_length=50)),
                ('co_pi_name', models.CharField(max_length=50)),
                ('co_pi_institute', models.CharField(max_length=50)),
                ('recommendation', models.CharField(choices=[('N', 'No Recommendation'), ('A', 'Accept'), ('M', 'Major Revision'), ('m', 'Minor Revision'), ('R', 'Reject')], max_length=17)),
                ('reviewer_comment', models.TextField()),
                ('reviewer_confidential_comment', models.TextField()),
                ('overall_ranking', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')])),
            ],
        ),
    ]
