# Generated by Django 4.2.2 on 2023-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='address',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='designation',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='institute',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='qualification',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
