# Generated by Django 4.2.3 on 2023-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_details_is_coordinator_details_is_pi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='is_pi',
            field=models.BooleanField(default=True),
        ),
    ]
