# Generated by Django 4.2.3 on 2023-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_details_is_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
